; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{C969FB06-BA18-4BF6-B172-408455D3F279}
AppName=prince of persia
AppVersion=1.5
;AppVerName=prince of persia 1.5
AppPublisher=unisoft
AppPublisherURL=https://www.unisoft.com
AppSupportURL=https://www.unisoft.com
AppUpdatesURL=https://www.unisoft.com
DefaultDirName=F:\New folder (2)\my site\PopSOT\pop
DefaultGroupName=prince of persia
AllowNoIcons=yes
OutputDir=F:\New folder (2)\my site\prince of persia setup
OutputBaseFilename=setup
SetupIconFile=F:\New folder (2)\my site\pop.ico
Compression=lzma
SolidCompression=yes
DiskSpanning=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked; OnlyBelowVersion: 0,6.1

[Files]
Source: "F:\New folder (2)\my site\PopSOT\POP.EXE"; DestDir: "{app}"; Flags: ignoreversion
Source: "F:\New folder (2)\my site\PopSOT\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\prince of persia"; Filename: "{app}\POP.EXE"
Name: "{commondesktop}\prince of persia"; Filename: "{app}\POP.EXE"; Tasks: desktopicon
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\prince of persia"; Filename: "{app}\POP.EXE"; Tasks: quicklaunchicon

[Run]
Filename: "{app}\POP.EXE"; Description: "{cm:LaunchProgram,prince of persia}"; Flags: nowait postinstall skipifsilent

